---
- name: "get template facts"
  stat:
    path: "{{ vm_template_dir }}/{{ vm_template }}"
    get_checksum: false
  register: vm_template_stats
  connection: local

- name: "download template"
  get_url:
    url: "{{ vm_template_download_url }}"
    dest: "{{ vm_template_dir }}/{{ vm_template }}"
    validate_certs: false
    mode: 0644
  when: not vm_template_stats.stat.exists
  run_once: true
  connection: local
