---
- include: download_vm_template.yml
  when: vm_provision_enabled
  tags:
    - provision

- include: provision_vm.yml
  when: vm_provision_enabled
  tags:
    - provision

- include: configure_vm.yml
  when: vm_configure_enabled
  tags:
    - configure
